function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "BarcoAbandonado", file = "media/maps/BarcoAbandonado/spawnpoints.lua" },
		{ name = "Factory", file = "media/maps/Factory/spawnpoints.lua" },
		{ name = "MilitaryComplex", file = "media/maps/MilitaryComplex/spawnpoints.lua" },
		{ name = "Riverside Gunstore", file = "media/maps/Riverside Gunstore/spawnpoints.lua" },
		{ name = "Mansion", file = "media/maps/Mansion/spawnpoints.lua" },
		{ name = "mechanicsplaces", file = "media/maps/mechanicsplaces/spawnpoints.lua" },
		{ name = "tluisville", file = "media/maps/tluisville/spawnpoints.lua" },
		{ name = "tmarch", file = "media/maps/tmarch/spawnpoints.lua" },
		{ name = "tvalley", file = "media/maps/tvalley/spawnpoints.lua" },
		{ name = "Gas Station", file = "media/maps/Gas Station/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "Masaii's old town", file = "media/maps/Masaii's old town/spawnpoints.lua" },
		{ name = "hq", file = "media/maps/hq/spawnpoints.lua" },
		{ name = "Xonics Mega Mall", file = "media/maps/Xonics Mega Mall/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Exterior", file = "media/maps/Xonics Mega Mall Exterior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Interior", file = "media/maps/Xonics Mega Mall Interior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Roof", file = "media/maps/Xonics Mega Mall Roof/spawnpoints.lua" },
		{ name = "west_point_expansion", file = "media/maps/west_point_expansion/spawnpoints.lua" },
	}
end
